var searchData=
[
  ['register_20offsets',['Register Offsets',['../group___a_d_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___a_e_s___k_e_y___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___a_e_s_k_e_y_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___d_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___d_v_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___f_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___f_l_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___g_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___g_p_i_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___h_t_m_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___i2_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___i_c_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___m_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___o_w_m___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_t_g___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_w_r_s_e_q___register___offsets.html',1,'']]],
  ['raminfo',['raminfo',['../group__usbhs__registers.html#a80910f238c57743c15928c0a4c72b342',1,'mxc_usbhs_regs_t']]],
  ['ras',['ras',['../group__htmr__registers.html#a1e8c3499c412ff58016b9199ead5b065',1,'mxc_htmr_regs_t']]],
  ['rate_5flength',['rate_length',['../group__pt__registers.html#a4731a4f820319edf87f6137bf131c7a1',1,'mxc_pt_regs_t']]],
  ['rawadcvalue',['rawADCValue',['../group__adc.html#aff64e9307e37a6c0c19849c52c753e67',1,'mxc_adc_conversion_req_t']]],
  ['read_5fnum',['read_num',['../group__spixf.html#a3fb91398a2b6ac9510a92590e80bf282',1,'mxc_spixf_req']]],
  ['read_5from_5fcommand',['READ_ROM_COMMAND',['../group__owm.html#gad1b5681de9d290630657044cd8e9d9f1',1,'owm.h']]],
  ['reload',['reload',['../group__wut__registers.html#ae7b291bdf41c8f597fdc59f9ef87c4a0',1,'mxc_wut_regs_t']]],
  ['reqsel',['reqsel',['../group__dma.html#afe25270cc6072325449821f64cd05b12',1,'mxc_dma_config_t']]],
  ['reqwait_5fen',['reqwait_en',['../group__dma.html#a3cc0364b140d69c23114b1c565ebe09e',1,'mxc_dma_adv_config_t']]],
  ['resp',['resp',['../group__sdhc__registers.html#ae0f2be736e906c905e819487bc5f3255',1,'mxc_sdhc_regs_t']]],
  ['restart',['restart',['../group__i2c.html#a9ebd0610b02b8fad4f28c6deadea0c7d',1,'_i2c_req_t::restart()'],['../group__pt__registers.html#a5c2af3e540f5418fad2dcd3530088eda',1,'mxc_pt_regs_t::restart()']]],
  ['resume_5fcommand',['RESUME_COMMAND',['../group__owm.html#ga16def8b56f538a3e221c279f176a28af',1,'owm.h']]],
  ['resync',['resync',['../group__ptg__registers.html#a44d9d228426e9049d9fc9638ecadfe59',1,'mxc_ptg_regs_t']]],
  ['revision',['revision',['../group__gcr__registers.html#ae93f00095baadabd87fea73087eb870a',1,'mxc_gcr_regs_t']]],
  ['rpu',['rpu',['../group__rpu__registers.html#a80c18f18149f48f860cd86bf8053f8fc',1,'mxc_rpu_regs_t::rpu()'],['../group__rpu.html',1,'(Global Namespace)']]],
  ['rpu_5fadc',['RPU_ADC',['../group___r_p_u___a_d_c.html',1,'']]],
  ['rpu_5faes',['RPU_AES',['../group___r_p_u___a_e_s.html',1,'']]],
  ['rpu_5faudio',['RPU_AUDIO',['../group___r_p_u___a_u_d_i_o.html',1,'']]],
  ['rpu_5fbtle',['RPU_BTLE',['../group___r_p_u___b_t_l_e.html',1,'']]],
  ['rpu_5fdma0',['RPU_DMA0',['../group___r_p_u___d_m_a0.html',1,'']]],
  ['rpu_5fdma1',['RPU_DMA1',['../group___r_p_u___d_m_a1.html',1,'']]],
  ['rpu_5fdvs',['RPU_DVS',['../group___r_p_u___d_v_s.html',1,'']]],
  ['rpu_5ffcr',['RPU_FCR',['../group___r_p_u___f_c_r.html',1,'']]],
  ['rpu_5fflc0',['RPU_FLC0',['../group___r_p_u___f_l_c0.html',1,'']]],
  ['rpu_5fflc1',['RPU_FLC1',['../group___r_p_u___f_l_c1.html',1,'']]],
  ['rpu_5fgcr',['RPU_GCR',['../group___r_p_u___g_c_r.html',1,'']]],
  ['rpu_5fgpio0',['RPU_GPIO0',['../group___r_p_u___g_p_i_o0.html',1,'']]],
  ['rpu_5fgpio1',['RPU_GPIO1',['../group___r_p_u___g_p_i_o1.html',1,'']]],
  ['rpu_5fhtimer0',['RPU_HTIMER0',['../group___r_p_u___h_t_i_m_e_r0.html',1,'']]],
  ['rpu_5fhtimer1',['RPU_HTIMER1',['../group___r_p_u___h_t_i_m_e_r1.html',1,'']]],
  ['rpu_5fi2c0_5fbus0',['RPU_I2C0_BUS0',['../group___r_p_u___i2_c0___b_u_s0.html',1,'']]],
  ['rpu_5fi2c0_5fbus1',['RPU_I2C0_BUS1',['../group___r_p_u___i2_c0___b_u_s1.html',1,'']]],
  ['rpu_5fi2c1_5fbus0',['RPU_I2C1_BUS0',['../group___r_p_u___i2_c1___b_u_s0.html',1,'']]],
  ['rpu_5fi2c1_5fbus1',['RPU_I2C1_BUS1',['../group___r_p_u___i2_c1___b_u_s1.html',1,'']]],
  ['rpu_5fi2c2_5fbus0',['RPU_I2C2_BUS0',['../group___r_p_u___i2_c2___b_u_s0.html',1,'']]],
  ['rpu_5fi2c2_5fbus1',['RPU_I2C2_BUS1',['../group___r_p_u___i2_c2___b_u_s1.html',1,'']]],
  ['rpu_5ficc0',['RPU_ICC0',['../group___r_p_u___i_c_c0.html',1,'']]],
  ['rpu_5ficc1',['RPU_ICC1',['../group___r_p_u___i_c_c1.html',1,'']]],
  ['rpu_5fmcr',['RPU_MCR',['../group___r_p_u___m_c_r.html',1,'']]],
  ['rpu_5fowm',['RPU_OWM',['../group___r_p_u___o_w_m.html',1,'']]],
  ['rpu_5fptg_5fbus0',['RPU_PTG_BUS0',['../group___r_p_u___p_t_g___b_u_s0.html',1,'']]],
  ['rpu_5fptg_5fbus1',['RPU_PTG_BUS1',['../group___r_p_u___p_t_g___b_u_s1.html',1,'']]],
  ['rpu_5fpwrseq',['RPU_PWRSEQ',['../group___r_p_u___p_w_r_s_e_q.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___r_p_u___register___offsets.html',1,'']]],
  ['rpu_5fregisters',['RPU_Registers',['../group__rpu__registers.html',1,'']]],
  ['rpu_5fregs_2eh',['rpu_regs.h',['../rpu__regs_8h.html',1,'']]],
  ['rpu_5frpu',['RPU_RPU',['../group___r_p_u___r_p_u.html',1,'']]],
  ['rpu_5frtc',['RPU_RTC',['../group___r_p_u___r_t_c.html',1,'']]],
  ['rpu_5fsdhcctrl',['RPU_SDHCCTRL',['../group___r_p_u___s_d_h_c_c_t_r_l.html',1,'']]],
  ['rpu_5fsdio',['RPU_SDIO',['../group___r_p_u___s_d_i_o.html',1,'']]],
  ['rpu_5fsdma',['RPU_SDMA',['../group___r_p_u___s_d_m_a.html',1,'']]],
  ['rpu_5fsema',['RPU_SEMA',['../group___r_p_u___s_e_m_a.html',1,'']]],
  ['rpu_5fsfcc',['RPU_SFCC',['../group___r_p_u___s_f_c_c.html',1,'']]],
  ['rpu_5fsimo',['RPU_SIMO',['../group___r_p_u___s_i_m_o.html',1,'']]],
  ['rpu_5fsir',['RPU_SIR',['../group___r_p_u___s_i_r.html',1,'']]],
  ['rpu_5fsmon',['RPU_SMON',['../group___r_p_u___s_m_o_n.html',1,'']]],
  ['rpu_5fspi0',['RPU_SPI0',['../group___r_p_u___s_p_i0.html',1,'']]],
  ['rpu_5fspi1',['RPU_SPI1',['../group___r_p_u___s_p_i1.html',1,'']]],
  ['rpu_5fspi2',['RPU_SPI2',['../group___r_p_u___s_p_i2.html',1,'']]],
  ['rpu_5fspixfc',['RPU_SPIXFC',['../group___r_p_u___s_p_i_x_f_c.html',1,'']]],
  ['rpu_5fspixfm',['RPU_SPIXFM',['../group___r_p_u___s_p_i_x_f_m.html',1,'']]],
  ['rpu_5fspixfm_5ffifo',['RPU_SPIXFM_FIFO',['../group___r_p_u___s_p_i_x_f_m___f_i_f_o.html',1,'']]],
  ['rpu_5fspixr',['RPU_SPIXR',['../group___r_p_u___s_p_i_x_r.html',1,'']]],
  ['rpu_5fsrcc',['RPU_SRCC',['../group___r_p_u___s_r_c_c.html',1,'']]],
  ['rpu_5fsysram0',['RPU_SYSRAM0',['../group___r_p_u___s_y_s_r_a_m0.html',1,'']]],
  ['rpu_5fsysram1',['RPU_SYSRAM1',['../group___r_p_u___s_y_s_r_a_m1.html',1,'']]],
  ['rpu_5fsysram2',['RPU_SYSRAM2',['../group___r_p_u___s_y_s_r_a_m2.html',1,'']]],
  ['rpu_5fsysram3',['RPU_SYSRAM3',['../group___r_p_u___s_y_s_r_a_m3.html',1,'']]],
  ['rpu_5fsysram4',['RPU_SYSRAM4',['../group___r_p_u___s_y_s_r_a_m4.html',1,'']]],
  ['rpu_5fsysram5',['RPU_SYSRAM5',['../group___r_p_u___s_y_s_r_a_m5.html',1,'']]],
  ['rpu_5fsysram6_5f11',['RPU_SYSRAM6_11',['../group___r_p_u___s_y_s_r_a_m6__11.html',1,'']]],
  ['rpu_5ftmr0',['RPU_TMR0',['../group___r_p_u___t_m_r0.html',1,'']]],
  ['rpu_5ftmr1',['RPU_TMR1',['../group___r_p_u___t_m_r1.html',1,'']]],
  ['rpu_5ftmr2',['RPU_TMR2',['../group___r_p_u___t_m_r2.html',1,'']]],
  ['rpu_5ftmr3',['RPU_TMR3',['../group___r_p_u___t_m_r3.html',1,'']]],
  ['rpu_5ftmr4',['RPU_TMR4',['../group___r_p_u___t_m_r4.html',1,'']]],
  ['rpu_5ftmr5',['RPU_TMR5',['../group___r_p_u___t_m_r5.html',1,'']]],
  ['rpu_5ftpu',['RPU_TPU',['../group___r_p_u___t_p_u.html',1,'']]],
  ['rpu_5ftrng',['RPU_TRNG',['../group___r_p_u___t_r_n_g.html',1,'']]],
  ['rpu_5fuart0',['RPU_UART0',['../group___r_p_u___u_a_r_t0.html',1,'']]],
  ['rpu_5fuart1',['RPU_UART1',['../group___r_p_u___u_a_r_t1.html',1,'']]],
  ['rpu_5fuart2',['RPU_UART2',['../group___r_p_u___u_a_r_t2.html',1,'']]],
  ['rpu_5fusbhs',['RPU_USBHS',['../group___r_p_u___u_s_b_h_s.html',1,'']]],
  ['rpu_5fwdt0',['RPU_WDT0',['../group___r_p_u___w_d_t0.html',1,'']]],
  ['rpu_5fwdt1',['RPU_WDT1',['../group___r_p_u___w_d_t1.html',1,'']]],
  ['rpu_5fwdt2',['RPU_WDT2',['../group___r_p_u___w_d_t2.html',1,'']]],
  ['rpu_5fwut',['RPU_WUT',['../group___r_p_u___w_u_t.html',1,'']]],
  ['rssa',['rssa',['../group__htmr__registers.html#a25b139283584cdc04b42627c9c28f90e',1,'mxc_htmr_regs_t']]],
  ['rst',['rst',['../group__wdt__registers.html#a5e60cc2ae13ed2a525bbee7118ac69cd',1,'mxc_wdt_regs_t']]],
  ['rstr0',['rstr0',['../group__gcr__registers.html#ac575e51b25af5e10d038847e87b3be78',1,'mxc_gcr_regs_t']]],
  ['rstr1',['rstr1',['../group__gcr__registers.html#a22b7d933839817506fac3d41e93d722a',1,'mxc_gcr_regs_t']]],
  ['rtc',['rtc',['../group__rpu__registers.html#a9a746db2451fb3ae05c8e0d596de0a9b',1,'mxc_rpu_regs_t::rtc()'],['../group__trimsir__registers.html#a9a746db2451fb3ae05c8e0d596de0a9b',1,'mxc_trimsir_regs_t::rtc()'],['../group__rtc.html',1,'(Global Namespace)']]],
  ['rtc_5fctrl',['RTC_CTRL',['../group___r_t_c___c_t_r_l.html',1,'']]],
  ['rtc_5foscctrl',['RTC_OSCCTRL',['../group___r_t_c___o_s_c_c_t_r_l.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___r_t_c___register___offsets.html',1,'']]],
  ['rtc_5fregisters',['RTC_Registers',['../group__rtc__registers.html',1,'']]],
  ['rtc_5fregs_2eh',['rtc_regs.h',['../rtc__regs_8h.html',1,'']]],
  ['rtc_5fsec',['RTC_SEC',['../group___r_t_c___s_e_c.html',1,'']]],
  ['rtc_5fssec',['RTC_SSEC',['../group___r_t_c___s_s_e_c.html',1,'']]],
  ['rtc_5fsseca',['RTC_SSECA',['../group___r_t_c___s_s_e_c_a.html',1,'']]],
  ['rtc_5ftoda',['RTC_TODA',['../group___r_t_c___t_o_d_a.html',1,'']]],
  ['rtc_5ftrim',['RTC_TRIM',['../group___r_t_c___t_r_i_m.html',1,'']]],
  ['rx_5f16',['rx_16',['../group__spixfc__fifo__registers.html#a1460c966d69174cbed64ed36f87a8f7b',1,'mxc_spixfc_fifo_regs_t']]],
  ['rx_5f32',['rx_32',['../group__spixfc__fifo__registers.html#a466dd110e3a361b8c2e51ab16ebb1dfb',1,'mxc_spixfc_fifo_regs_t']]],
  ['rx_5f8',['rx_8',['../group__spixfc__fifo__registers.html#aa071e7c222293eb2250d1d56d32ec6d4',1,'mxc_spixfc_fifo_regs_t']]],
  ['rx_5fbuf',['rx_buf',['../group__i2c.html#a62d96b3e83f506af2c4c5c1ddfd3c785',1,'_i2c_req_t']]],
  ['rx_5fctrl0',['rx_ctrl0',['../group__i2c__registers.html#abaab2a23f646788de6ec203e99f31efb',1,'mxc_i2c_regs_t']]],
  ['rx_5fctrl1',['rx_ctrl1',['../group__i2c__registers.html#a5ad14aae2fb3f385707381d5e378ac31',1,'mxc_i2c_regs_t']]],
  ['rx_5fdata',['rx_data',['../group__spixf.html#a8a4e2302651974da84f7b9904e8e1914',1,'mxc_spixf_req']]],
  ['rx_5flen',['rx_len',['../group__i2c.html#a7d1a4ab0355b90b84277c05f75119f55',1,'_i2c_req_t']]],
  ['rxcnt',['rxCnt',['../group__spi.html#a1bf34bc0d63b8e4a68fa9fb295b03f34',1,'_mxc_spi_req_t::rxCnt()'],['../group__uart.html#a5170bf9ee63cd6a1605360b56257439e',1,'_mxc_uart_req_t::rxCnt()']]],
  ['rxdata',['rxData',['../group__spi.html#ab83c0e07099df7beb8e491cb91914de0',1,'_mxc_spi_req_t::rxData()'],['../group__uart.html#ab83c0e07099df7beb8e491cb91914de0',1,'_mxc_uart_req_t::rxData()']]],
  ['rxlen',['rxLen',['../group__spi.html#a043f0f3e53b8233dca0b9446b9c36ccd',1,'_mxc_spi_req_t::rxLen()'],['../group__uart.html#a043f0f3e53b8233dca0b9446b9c36ccd',1,'_mxc_uart_req_t::rxLen()']]],
  ['register_20offsets',['Register Offsets',['../group___s_d_h_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_d_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_e_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_i_m_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_i_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_m_o_n___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_c___f_i_f_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_m___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_r_c_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_m_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_p_u___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_r_i_m_s_i_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_r_n_g___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___u_a_r_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___u_s_b_h_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___w_d_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___w_u_t___register___offsets.html',1,'']]]
];
