var searchData=
[
  ['register_20offsets',['Register Offsets',['../group___a_d_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___a_e_s___k_e_y___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___a_e_s_k_e_y_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___d_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___d_v_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___f_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___f_l_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___g_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___g_p_i_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___h_t_m_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___i2_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___i_c_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___m_c_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___o_w_m___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_t_g___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___p_w_r_s_e_q___register___offsets.html',1,'']]],
  ['resource_20protection_20unit',['Resource Protection Unit',['../group__rpu.html',1,'']]],
  ['rpu_5fadc',['RPU_ADC',['../group___r_p_u___a_d_c.html',1,'']]],
  ['rpu_5faes',['RPU_AES',['../group___r_p_u___a_e_s.html',1,'']]],
  ['rpu_5faudio',['RPU_AUDIO',['../group___r_p_u___a_u_d_i_o.html',1,'']]],
  ['rpu_5fbtle',['RPU_BTLE',['../group___r_p_u___b_t_l_e.html',1,'']]],
  ['rpu_5fdma0',['RPU_DMA0',['../group___r_p_u___d_m_a0.html',1,'']]],
  ['rpu_5fdma1',['RPU_DMA1',['../group___r_p_u___d_m_a1.html',1,'']]],
  ['rpu_5fdvs',['RPU_DVS',['../group___r_p_u___d_v_s.html',1,'']]],
  ['rpu_5ffcr',['RPU_FCR',['../group___r_p_u___f_c_r.html',1,'']]],
  ['rpu_5fflc0',['RPU_FLC0',['../group___r_p_u___f_l_c0.html',1,'']]],
  ['rpu_5fflc1',['RPU_FLC1',['../group___r_p_u___f_l_c1.html',1,'']]],
  ['rpu_5fgcr',['RPU_GCR',['../group___r_p_u___g_c_r.html',1,'']]],
  ['rpu_5fgpio0',['RPU_GPIO0',['../group___r_p_u___g_p_i_o0.html',1,'']]],
  ['rpu_5fgpio1',['RPU_GPIO1',['../group___r_p_u___g_p_i_o1.html',1,'']]],
  ['rpu_5fhtimer0',['RPU_HTIMER0',['../group___r_p_u___h_t_i_m_e_r0.html',1,'']]],
  ['rpu_5fhtimer1',['RPU_HTIMER1',['../group___r_p_u___h_t_i_m_e_r1.html',1,'']]],
  ['rpu_5fi2c0_5fbus0',['RPU_I2C0_BUS0',['../group___r_p_u___i2_c0___b_u_s0.html',1,'']]],
  ['rpu_5fi2c0_5fbus1',['RPU_I2C0_BUS1',['../group___r_p_u___i2_c0___b_u_s1.html',1,'']]],
  ['rpu_5fi2c1_5fbus0',['RPU_I2C1_BUS0',['../group___r_p_u___i2_c1___b_u_s0.html',1,'']]],
  ['rpu_5fi2c1_5fbus1',['RPU_I2C1_BUS1',['../group___r_p_u___i2_c1___b_u_s1.html',1,'']]],
  ['rpu_5fi2c2_5fbus0',['RPU_I2C2_BUS0',['../group___r_p_u___i2_c2___b_u_s0.html',1,'']]],
  ['rpu_5fi2c2_5fbus1',['RPU_I2C2_BUS1',['../group___r_p_u___i2_c2___b_u_s1.html',1,'']]],
  ['rpu_5ficc0',['RPU_ICC0',['../group___r_p_u___i_c_c0.html',1,'']]],
  ['rpu_5ficc1',['RPU_ICC1',['../group___r_p_u___i_c_c1.html',1,'']]],
  ['rpu_5fmcr',['RPU_MCR',['../group___r_p_u___m_c_r.html',1,'']]],
  ['rpu_5fowm',['RPU_OWM',['../group___r_p_u___o_w_m.html',1,'']]],
  ['rpu_5fptg_5fbus0',['RPU_PTG_BUS0',['../group___r_p_u___p_t_g___b_u_s0.html',1,'']]],
  ['rpu_5fptg_5fbus1',['RPU_PTG_BUS1',['../group___r_p_u___p_t_g___b_u_s1.html',1,'']]],
  ['rpu_5fpwrseq',['RPU_PWRSEQ',['../group___r_p_u___p_w_r_s_e_q.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___r_p_u___register___offsets.html',1,'']]],
  ['rpu_5fregisters',['RPU_Registers',['../group__rpu__registers.html',1,'']]],
  ['rpu_5frpu',['RPU_RPU',['../group___r_p_u___r_p_u.html',1,'']]],
  ['rpu_5frtc',['RPU_RTC',['../group___r_p_u___r_t_c.html',1,'']]],
  ['rpu_5fsdhcctrl',['RPU_SDHCCTRL',['../group___r_p_u___s_d_h_c_c_t_r_l.html',1,'']]],
  ['rpu_5fsdio',['RPU_SDIO',['../group___r_p_u___s_d_i_o.html',1,'']]],
  ['rpu_5fsdma',['RPU_SDMA',['../group___r_p_u___s_d_m_a.html',1,'']]],
  ['rpu_5fsema',['RPU_SEMA',['../group___r_p_u___s_e_m_a.html',1,'']]],
  ['rpu_5fsfcc',['RPU_SFCC',['../group___r_p_u___s_f_c_c.html',1,'']]],
  ['rpu_5fsimo',['RPU_SIMO',['../group___r_p_u___s_i_m_o.html',1,'']]],
  ['rpu_5fsir',['RPU_SIR',['../group___r_p_u___s_i_r.html',1,'']]],
  ['rpu_5fsmon',['RPU_SMON',['../group___r_p_u___s_m_o_n.html',1,'']]],
  ['rpu_5fspi0',['RPU_SPI0',['../group___r_p_u___s_p_i0.html',1,'']]],
  ['rpu_5fspi1',['RPU_SPI1',['../group___r_p_u___s_p_i1.html',1,'']]],
  ['rpu_5fspi2',['RPU_SPI2',['../group___r_p_u___s_p_i2.html',1,'']]],
  ['rpu_5fspixfc',['RPU_SPIXFC',['../group___r_p_u___s_p_i_x_f_c.html',1,'']]],
  ['rpu_5fspixfm',['RPU_SPIXFM',['../group___r_p_u___s_p_i_x_f_m.html',1,'']]],
  ['rpu_5fspixfm_5ffifo',['RPU_SPIXFM_FIFO',['../group___r_p_u___s_p_i_x_f_m___f_i_f_o.html',1,'']]],
  ['rpu_5fspixr',['RPU_SPIXR',['../group___r_p_u___s_p_i_x_r.html',1,'']]],
  ['rpu_5fsrcc',['RPU_SRCC',['../group___r_p_u___s_r_c_c.html',1,'']]],
  ['rpu_5fsysram0',['RPU_SYSRAM0',['../group___r_p_u___s_y_s_r_a_m0.html',1,'']]],
  ['rpu_5fsysram1',['RPU_SYSRAM1',['../group___r_p_u___s_y_s_r_a_m1.html',1,'']]],
  ['rpu_5fsysram2',['RPU_SYSRAM2',['../group___r_p_u___s_y_s_r_a_m2.html',1,'']]],
  ['rpu_5fsysram3',['RPU_SYSRAM3',['../group___r_p_u___s_y_s_r_a_m3.html',1,'']]],
  ['rpu_5fsysram4',['RPU_SYSRAM4',['../group___r_p_u___s_y_s_r_a_m4.html',1,'']]],
  ['rpu_5fsysram5',['RPU_SYSRAM5',['../group___r_p_u___s_y_s_r_a_m5.html',1,'']]],
  ['rpu_5fsysram6_5f11',['RPU_SYSRAM6_11',['../group___r_p_u___s_y_s_r_a_m6__11.html',1,'']]],
  ['rpu_5ftmr0',['RPU_TMR0',['../group___r_p_u___t_m_r0.html',1,'']]],
  ['rpu_5ftmr1',['RPU_TMR1',['../group___r_p_u___t_m_r1.html',1,'']]],
  ['rpu_5ftmr2',['RPU_TMR2',['../group___r_p_u___t_m_r2.html',1,'']]],
  ['rpu_5ftmr3',['RPU_TMR3',['../group___r_p_u___t_m_r3.html',1,'']]],
  ['rpu_5ftmr4',['RPU_TMR4',['../group___r_p_u___t_m_r4.html',1,'']]],
  ['rpu_5ftmr5',['RPU_TMR5',['../group___r_p_u___t_m_r5.html',1,'']]],
  ['rpu_5ftpu',['RPU_TPU',['../group___r_p_u___t_p_u.html',1,'']]],
  ['rpu_5ftrng',['RPU_TRNG',['../group___r_p_u___t_r_n_g.html',1,'']]],
  ['rpu_5fuart0',['RPU_UART0',['../group___r_p_u___u_a_r_t0.html',1,'']]],
  ['rpu_5fuart1',['RPU_UART1',['../group___r_p_u___u_a_r_t1.html',1,'']]],
  ['rpu_5fuart2',['RPU_UART2',['../group___r_p_u___u_a_r_t2.html',1,'']]],
  ['rpu_5fusbhs',['RPU_USBHS',['../group___r_p_u___u_s_b_h_s.html',1,'']]],
  ['rpu_5fwdt0',['RPU_WDT0',['../group___r_p_u___w_d_t0.html',1,'']]],
  ['rpu_5fwdt1',['RPU_WDT1',['../group___r_p_u___w_d_t1.html',1,'']]],
  ['rpu_5fwdt2',['RPU_WDT2',['../group___r_p_u___w_d_t2.html',1,'']]],
  ['rpu_5fwut',['RPU_WUT',['../group___r_p_u___w_u_t.html',1,'']]],
  ['real_20time_20clock_20_28rtc_29',['Real Time Clock (RTC)',['../group__rtc.html',1,'']]],
  ['rtc_5fctrl',['RTC_CTRL',['../group___r_t_c___c_t_r_l.html',1,'']]],
  ['rtc_5foscctrl',['RTC_OSCCTRL',['../group___r_t_c___o_s_c_c_t_r_l.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___r_t_c___register___offsets.html',1,'']]],
  ['rtc_5fregisters',['RTC_Registers',['../group__rtc__registers.html',1,'']]],
  ['rtc_5fsec',['RTC_SEC',['../group___r_t_c___s_e_c.html',1,'']]],
  ['rtc_5fssec',['RTC_SSEC',['../group___r_t_c___s_s_e_c.html',1,'']]],
  ['rtc_5fsseca',['RTC_SSECA',['../group___r_t_c___s_s_e_c_a.html',1,'']]],
  ['rtc_5ftoda',['RTC_TODA',['../group___r_t_c___t_o_d_a.html',1,'']]],
  ['rtc_5ftrim',['RTC_TRIM',['../group___r_t_c___t_r_i_m.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_d_h_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_d_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_e_m_a___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_i_m_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_i_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_m_o_n___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_c___f_i_f_o___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_f_m___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_p_i_x_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___s_r_c_c___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_m_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_p_u___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_r_i_m_s_i_r___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___t_r_n_g___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___u_a_r_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___u_s_b_h_s___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___w_d_t___register___offsets.html',1,'']]],
  ['register_20offsets',['Register Offsets',['../group___w_u_t___register___offsets.html',1,'']]]
];
