var searchData=
[
  ['system_20configuration_20_28mxc_5fsys_29',['System Configuration (MXC_SYS)',['../group__mxc__sys.html',1,'']]],
  ['semaphore_20_28sema_29',['Semaphore (SEMA)',['../group__sema.html',1,'']]],
  ['sema_5firq0',['SEMA_IRQ0',['../group___s_e_m_a___i_r_q0.html',1,'']]],
  ['sema_5firq1',['SEMA_IRQ1',['../group___s_e_m_a___i_r_q1.html',1,'']]],
  ['sema_5fmail0',['SEMA_MAIL0',['../group___s_e_m_a___m_a_i_l0.html',1,'']]],
  ['sema_5fmail1',['SEMA_MAIL1',['../group___s_e_m_a___m_a_i_l1.html',1,'']]],
  ['sema_5fregisters',['SEMA_Registers',['../group__sema__registers.html',1,'']]],
  ['sema_5fsemaphores',['SEMA_SEMAPHORES',['../group___s_e_m_a___s_e_m_a_p_h_o_r_e_s.html',1,'']]],
  ['sema_5fstatus',['SEMA_STATUS',['../group___s_e_m_a___s_t_a_t_u_s.html',1,'']]],
  ['sir_5fbtle_5fldo_5ftrim',['SIR_BTLE_LDO_TRIM',['../group___s_i_r___b_t_l_e___l_d_o___t_r_i_m.html',1,'']]],
  ['sir_5ffstat',['SIR_FSTAT',['../group___s_i_r___f_s_t_a_t.html',1,'']]],
  ['sir_5fregisters',['SIR_Registers',['../group__sir__registers.html',1,'']]],
  ['sir_5fsfstat',['SIR_SFSTAT',['../group___s_i_r___s_f_s_t_a_t.html',1,'']]],
  ['sir_5fsiaddr',['SIR_SIADDR',['../group___s_i_r___s_i_a_d_d_r.html',1,'']]],
  ['sir_5fsistat',['SIR_SISTAT',['../group___s_i_r___s_i_s_t_a_t.html',1,'']]],
  ['smon_5fdlrtc',['SMON_DLRTC',['../group___s_m_o_n___d_l_r_t_c.html',1,'']]],
  ['smon_5fextscn',['SMON_EXTSCN',['../group___s_m_o_n___e_x_t_s_c_n.html',1,'']]],
  ['smon_5fintscn',['SMON_INTSCN',['../group___s_m_o_n___i_n_t_s_c_n.html',1,'']]],
  ['smon_5fmeucfg',['SMON_MEUCFG',['../group___s_m_o_n___m_e_u_c_f_g.html',1,'']]],
  ['smon_5fregisters',['SMON_Registers',['../group__smon__registers.html',1,'']]],
  ['smon_5fsdbe',['SMON_SDBE',['../group___s_m_o_n___s_d_b_e.html',1,'']]],
  ['smon_5fsecalm',['SMON_SECALM',['../group___s_m_o_n___s_e_c_a_l_m.html',1,'']]],
  ['smon_5fsecdiag',['SMON_SECDIAG',['../group___s_m_o_n___s_e_c_d_i_a_g.html',1,'']]],
  ['smon_5fsecst',['SMON_SECST',['../group___s_m_o_n___s_e_c_s_t.html',1,'']]],
  ['spi',['SPI',['../group__spi.html',1,'']]],
  ['spi_5fclkctrl',['SPI_CLKCTRL',['../group___s_p_i___c_l_k_c_t_r_l.html',1,'']]],
  ['spi_5fctrl0',['SPI_CTRL0',['../group___s_p_i___c_t_r_l0.html',1,'']]],
  ['spi_5fctrl1',['SPI_CTRL1',['../group___s_p_i___c_t_r_l1.html',1,'']]],
  ['spi_5fctrl2',['SPI_CTRL2',['../group___s_p_i___c_t_r_l2.html',1,'']]],
  ['spi_5fdma',['SPI_DMA',['../group___s_p_i___d_m_a.html',1,'']]],
  ['spi_5ffifo16',['SPI_FIFO16',['../group___s_p_i___f_i_f_o16.html',1,'']]],
  ['spi_5ffifo32',['SPI_FIFO32',['../group___s_p_i___f_i_f_o32.html',1,'']]],
  ['spi_5ffifo8',['SPI_FIFO8',['../group___s_p_i___f_i_f_o8.html',1,'']]],
  ['spi_5finten',['SPI_INTEN',['../group___s_p_i___i_n_t_e_n.html',1,'']]],
  ['spi_5fintfl',['SPI_INTFL',['../group___s_p_i___i_n_t_f_l.html',1,'']]],
  ['spi_5fregisters',['SPI_Registers',['../group__spi__registers.html',1,'']]],
  ['spi_5fsstime',['SPI_SSTIME',['../group___s_p_i___s_s_t_i_m_e.html',1,'']]],
  ['spi_5fstat',['SPI_STAT',['../group___s_p_i___s_t_a_t.html',1,'']]],
  ['spi_5fwken',['SPI_WKEN',['../group___s_p_i___w_k_e_n.html',1,'']]],
  ['spi_5fwkfl',['SPI_WKFL',['../group___s_p_i___w_k_f_l.html',1,'']]],
  ['spi_20external_20flash_20_28spixf_29',['SPI External Flash (SPIXF)',['../group__spixf.html',1,'']]],
  ['spi_20external_20flash_20controller_20_28spixfc_29',['SPI External Flash Controller (SPIXFC)',['../group__spixfc.html',1,'']]],
  ['spixfc_5fctrl0',['SPIXFC_CTRL0',['../group___s_p_i_x_f_c___c_t_r_l0.html',1,'']]],
  ['spixfc_5fctrl1',['SPIXFC_CTRL1',['../group___s_p_i_x_f_c___c_t_r_l1.html',1,'']]],
  ['spixfc_5fctrl2',['SPIXFC_CTRL2',['../group___s_p_i_x_f_c___c_t_r_l2.html',1,'']]],
  ['spixfc_5fctrl3',['SPIXFC_CTRL3',['../group___s_p_i_x_f_c___c_t_r_l3.html',1,'']]],
  ['spi_20external_20flash_20controller_20fifo_20_28spixfc_5ffifo_29',['SPI External Flash Controller FIFO (SPIXFC_FIFO)',['../group__spixfc__fifo.html',1,'']]],
  ['spixfc_5ffifo_5fregisters',['SPIXFC_FIFO_Registers',['../group__spixfc__fifo__registers.html',1,'']]],
  ['spixfc_5finten',['SPIXFC_INTEN',['../group___s_p_i_x_f_c___i_n_t_e_n.html',1,'']]],
  ['spixfc_5fintfl',['SPIXFC_INTFL',['../group___s_p_i_x_f_c___i_n_t_f_l.html',1,'']]],
  ['spixfc_5fregisters',['SPIXFC_Registers',['../group__spixfc__registers.html',1,'']]],
  ['spixfc_5fsimple_5fheader',['SPIXFC_SIMPLE_HEADER',['../group___s_p_i_x_f_c___s_i_m_p_l_e___h_e_a_d_e_r.html',1,'']]],
  ['spixfc_5fsspol',['SPIXFC_SSPOL',['../group___s_p_i_x_f_c___s_s_p_o_l.html',1,'']]],
  ['spi_20external_20flash_20master_20_28spixfm_29',['SPI External Flash Master (SPIXFM)',['../group__spixfm.html',1,'']]],
  ['spixfm_5fbusidle',['SPIXFM_BUSIDLE',['../group___s_p_i_x_f_m___b_u_s_i_d_l_e.html',1,'']]],
  ['spixfm_5fctrl',['SPIXFM_CTRL',['../group___s_p_i_x_f_m___c_t_r_l.html',1,'']]],
  ['spixfm_5ffbctrl',['SPIXFM_FBCTRL',['../group___s_p_i_x_f_m___f_b_c_t_r_l.html',1,'']]],
  ['spixfm_5ffetchctrl',['SPIXFM_FETCHCTRL',['../group___s_p_i_x_f_m___f_e_t_c_h_c_t_r_l.html',1,'']]],
  ['spixfm_5fioctrl',['SPIXFM_IOCTRL',['../group___s_p_i_x_f_m___i_o_c_t_r_l.html',1,'']]],
  ['spixfm_5fmemsecctrl',['SPIXFM_MEMSECCTRL',['../group___s_p_i_x_f_m___m_e_m_s_e_c_c_t_r_l.html',1,'']]],
  ['spixfm_5fmodectrl',['SPIXFM_MODECTRL',['../group___s_p_i_x_f_m___m_o_d_e_c_t_r_l.html',1,'']]],
  ['spixfm_5fmodedata',['SPIXFM_MODEDATA',['../group___s_p_i_x_f_m___m_o_d_e_d_a_t_a.html',1,'']]],
  ['spixfm_5fregisters',['SPIXFM_Registers',['../group__spixfm__registers.html',1,'']]],
  ['spi_20external_20ram_20_28spixr_29',['SPI External RAM (SPIXR)',['../group__spixr.html',1,'']]],
  ['spixr_5fbrgctrl',['SPIXR_BRGCTRL',['../group___s_p_i_x_r___b_r_g_c_t_r_l.html',1,'']]],
  ['spixr_5fctrl0',['SPIXR_CTRL0',['../group___s_p_i_x_r___c_t_r_l0.html',1,'']]],
  ['spixr_5fctrl1',['SPIXR_CTRL1',['../group___s_p_i_x_r___c_t_r_l1.html',1,'']]],
  ['spixr_5fctrl2',['SPIXR_CTRL2',['../group___s_p_i_x_r___c_t_r_l2.html',1,'']]],
  ['spixr_5fctrl3',['SPIXR_CTRL3',['../group___s_p_i_x_r___c_t_r_l3.html',1,'']]],
  ['spixr_5fdata16',['SPIXR_DATA16',['../group___s_p_i_x_r___d_a_t_a16.html',1,'']]],
  ['spixr_5fdata32',['SPIXR_DATA32',['../group___s_p_i_x_r___d_a_t_a32.html',1,'']]],
  ['spixr_5fdata8',['SPIXR_DATA8',['../group___s_p_i_x_r___d_a_t_a8.html',1,'']]],
  ['spixr_5fdma',['SPIXR_DMA',['../group___s_p_i_x_r___d_m_a.html',1,'']]],
  ['spixr_5finten',['SPIXR_INTEN',['../group___s_p_i_x_r___i_n_t_e_n.html',1,'']]],
  ['spixr_5fintfl',['SPIXR_INTFL',['../group___s_p_i_x_r___i_n_t_f_l.html',1,'']]],
  ['spixr_5fregisters',['SPIXR_Registers',['../group__spixr__registers.html',1,'']]],
  ['spixr_5fstat',['SPIXR_STAT',['../group___s_p_i_x_r___s_t_a_t.html',1,'']]],
  ['spixr_5fwken',['SPIXR_WKEN',['../group___s_p_i_x_r___w_k_e_n.html',1,'']]],
  ['spixr_5fwkfl',['SPIXR_WKFL',['../group___s_p_i_x_r___w_k_f_l.html',1,'']]],
  ['spixr_5fxmemctrl',['SPIXR_XMEMCTRL',['../group___s_p_i_x_r___x_m_e_m_c_t_r_l.html',1,'']]]
];
