var searchData=
[
  ['system_20configuration_20_28mxc_5fsys_29',['System Configuration (MXC_SYS)',['../group__mxc__sys.html',1,'']]],
  ['serial_20flash_20emulator_20_28sfe_29',['Serial Flash Emulator (SFE)',['../group__sfe.html',1,'']]],
  ['sfe_5fcfg',['SFE_CFG',['../group___s_f_e___c_f_g.html',1,'']]],
  ['sfe_5fflash_5fsba',['SFE_FLASH_SBA',['../group___s_f_e___f_l_a_s_h___s_b_a.html',1,'']]],
  ['sfe_5fflash_5fsta',['SFE_FLASH_STA',['../group___s_f_e___f_l_a_s_h___s_t_a.html',1,'']]],
  ['sfe_5fhfsa',['SFE_HFSA',['../group___s_f_e___h_f_s_a.html',1,'']]],
  ['sfe_5fhrsa',['SFE_HRSA',['../group___s_f_e___h_r_s_a.html',1,'']]],
  ['sfe_5fram_5fsba',['SFE_RAM_SBA',['../group___s_f_e___r_a_m___s_b_a.html',1,'']]],
  ['sfe_5fram_5fsta',['SFE_RAM_STA',['../group___s_f_e___r_a_m___s_t_a.html',1,'']]],
  ['sfe_5fregisters',['SFE_Registers',['../group__sfe__registers.html',1,'']]],
  ['sfe_5fsfdp_5fsba',['SFE_SFDP_SBA',['../group___s_f_e___s_f_d_p___s_b_a.html',1,'']]],
  ['sir_5ferraddr',['SIR_ERRADDR',['../group___s_i_r___e_r_r_a_d_d_r.html',1,'']]],
  ['sir_5ffstat',['SIR_FSTAT',['../group___s_i_r___f_s_t_a_t.html',1,'']]],
  ['sir_5fregisters',['SIR_Registers',['../group__sir__registers.html',1,'']]],
  ['sir_5fsfstat',['SIR_SFSTAT',['../group___s_i_r___s_f_s_t_a_t.html',1,'']]],
  ['sir_5fsistat',['SIR_SISTAT',['../group___s_i_r___s_i_s_t_a_t.html',1,'']]],
  ['security_20monitor_28smon_29',['Security Monitor(SMON)',['../group__smon.html',1,'']]],
  ['smon_5fextscn',['SMON_EXTSCN',['../group___s_m_o_n___e_x_t_s_c_n.html',1,'']]],
  ['smon_5fintscn',['SMON_INTSCN',['../group___s_m_o_n___i_n_t_s_c_n.html',1,'']]],
  ['smon_5fregisters',['SMON_Registers',['../group__smon__registers.html',1,'']]],
  ['smon_5fsdbe',['SMON_SDBE',['../group___s_m_o_n___s_d_b_e.html',1,'']]],
  ['smon_5fsecalm',['SMON_SECALM',['../group___s_m_o_n___s_e_c_a_l_m.html',1,'']]],
  ['smon_5fsecdiag',['SMON_SECDIAG',['../group___s_m_o_n___s_e_c_d_i_a_g.html',1,'']]],
  ['smon_5fsecst',['SMON_SECST',['../group___s_m_o_n___s_e_c_s_t.html',1,'']]],
  ['spi',['SPI',['../group__spi.html',1,'']]],
  ['spi_5fclk_5fconfig',['SPI_CLK_CONFIG',['../group___s_p_i___c_l_k___c_o_n_f_i_g.html',1,'']]],
  ['spi_5fdata16',['SPI_DATA16',['../group___s_p_i___d_a_t_a16.html',1,'']]],
  ['spi_5fdata32',['SPI_DATA32',['../group___s_p_i___d_a_t_a32.html',1,'']]],
  ['spi_5fdata8',['SPI_DATA8',['../group___s_p_i___d_a_t_a8.html',1,'']]],
  ['spi_5fdma',['SPI_DMA',['../group___s_p_i___d_m_a.html',1,'']]],
  ['spi_5fint_5fen',['SPI_INT_EN',['../group___s_p_i___i_n_t___e_n.html',1,'']]],
  ['spi_5fint_5ffl',['SPI_INT_FL',['../group___s_p_i___i_n_t___f_l.html',1,'']]],
  ['spi_5fmstr_5fcntl',['SPI_MSTR_CNTL',['../group___s_p_i___m_s_t_r___c_n_t_l.html',1,'']]],
  ['spi_5fregisters',['SPI_Registers',['../group__spi__registers.html',1,'']]],
  ['spi_5fss_5ftime',['SPI_SS_TIME',['../group___s_p_i___s_s___t_i_m_e.html',1,'']]],
  ['spi_5fstat',['SPI_STAT',['../group___s_p_i___s_t_a_t.html',1,'']]],
  ['spi_5fstatic_5fconfig',['SPI_STATIC_CONFIG',['../group___s_p_i___s_t_a_t_i_c___c_o_n_f_i_g.html',1,'']]],
  ['spi_5ftrnmt_5fsize',['SPI_TRNMT_SIZE',['../group___s_p_i___t_r_n_m_t___s_i_z_e.html',1,'']]],
  ['spi_5fwake_5fen',['SPI_WAKE_EN',['../group___s_p_i___w_a_k_e___e_n.html',1,'']]],
  ['spi_5fwake_5ffl',['SPI_WAKE_FL',['../group___s_p_i___w_a_k_e___f_l.html',1,'']]]
];
